# -*- coding: utf-8 -*-
"""2014893_SOURAVGUPTA_74_DS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LEvQhrE4URcCzdy9009t9BRiTdj85pn0
"""

# Import Libraries

import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import CountVectorizer

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score , confusion_matrix

"""## Load Dataset"""

data = pd.read_csv('dataset.csv')
data

data = data.drop(['URLs'] ,axis=1)

data = data.dropna()

"""## Classifier"""

## Classifier
cv = CountVectorizer()

hd = cv.fit_transform(data.iloc[:,0].values).todense()
by = cv.fit_transform(data.iloc[:,1].values).todense()

X = np.hstack((hd,by))
y = data['Label']

"""## Train Test Split"""

X_train ,X_test ,y_train ,y_test = train_test_split(X,y,test_size=0.3,random_state=0)

"""## Model"""

model = DecisionTreeClassifier(criterion='entropy')

model.fit(X_train,y_train)

y_pred = model.predict(X_test)

"""## Accuracy of model"""

accuracy = accuracy_score(y_test,y_pred)
accuracy

confusion_matrix(y_test,y_pred)

